### ISSUE TITLE
Regarding NOTES

### ISSUE THREAD

**Issue by Kaap10** [BCAPATHSHALA/DSA-SUPREME-2-0-NOTES#1]
Notes not opening? neither downloading? on GitHub web

kindly help

**Comment by BCAPATHSHALA** [comment]
we will resolve this issue soon. Thanks for informing us

**Comment by BCAPATHSHALA** [comment]
> Notes not opening? neither downloading? on GitHub web
> 
> kindly help

we will resolve this issue soon. Thanks for informing us

**Comment by Kaap10** [comment]
better to upload Only Notes part in Google drive.. that will be helpful
